export const AppErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  INVALID_FILE: "INVALID_FILE",
  RATE_LIMITED: "RATE_LIMITED",
  WHATSAPP_NOT_CONNECTED: "WHATSAPP_NOT_CONNECTED",
  AI_LIMIT_REACHED: "AI_LIMIT_REACHED",
  DOMAIN_NOT_VERIFIED: "DOMAIN_NOT_VERIFIED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type AppErrorCode = keyof typeof AppErrorCodes;
