import { z } from "zod";

export const businessSchema = z.object({
  name: z.string().min(2, "El nombre debe tener al menos 2 caracteres"),
  subdomain: z.string().min(3, "El subdominio debe tener al menos 3 caracteres").regex(/^[a-z0-9-]+$/, "Solo minúsculas, números y guiones"),
  email: z.string().email("Debe ser un email válido"),
  customDomain: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  type: z.string().optional().default("general"),
  status: z.string().optional().default("TRIAL"),
  paymentAmount: z.union([z.string(), z.number()]).optional().default(0).transform(val => Number(val)),
  paymentStatus: z.string().optional().default("pending"),
});

export const businessUpdateSchema = z.object({
  name: z.string().min(2).optional(),
  subdomain: z.string().optional(),
  email: z.string().email().optional().nullable(),
  phone: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  type: z.string().optional(),
  status: z.string().optional(),
  paymentAmount: z.union([z.string(), z.number()]).optional().transform(val => val !== undefined ? Number(val) : undefined),
  paymentStatus: z.string().optional(),
  demoExpiresAt: z.any().optional(),
  nextPayment: z.any().optional(),
  accentColor: z.string().optional(),
  primaryColor: z.string().optional(),
  secondaryColor: z.string().optional(),
  fontFamily: z.string().optional(),
  logoUrl: z.string().optional().nullable(),
  bannerUrl: z.string().optional().nullable(),
  layoutConfig: z.any().optional(),
  paymentData: z.any().optional(),
  customDomain: z.string().optional().nullable(),
  instagram: z.string().optional().nullable(),
  facebook: z.string().optional().nullable(),
  whatsapp: z.string().optional().nullable(),
  tiktok: z.string().optional().nullable(),
});

export const appointmentSchema = z.object({
  businessId: z.string().min(1, "businessId es requerido"),
  clientName: z.string().min(2, "Nombre requerido"),
  clientPhone: z.string().min(6, "Teléfono requerido"),
  clientEmail: z.string().email("Email inválido").optional().nullable(),
  date: z.string().or(z.date()).transform(val => new Date(val)),
  status: z.string().optional().default("PENDING"),
  serviceName: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  patente: z.string().optional().nullable(),
  employeeId: z.string().optional().nullable(),
  paymentMethod: z.string().optional().default("LOCAL"),
  paymentReference: z.string().optional().nullable(),
});
